### ISSUE TITLE
Not using the scoop correct path

### ISSUE THREAD

**Issue by MarioGK** [plicit/scoop-search-multisource#2]
```
PS C:\Users\mariogk> scoop-search-multisource.exe qbittorrent
____________________
#1 Searching  [buckets] C:\Users\mariogk\scoop\buckets
2022/07/23 01:43:29 Buckets folder does not exist - open C:\Users\mariogk\scoop\buckets: The system cannot find the path specified.
```
It is trying to use the default buckets path, but if you set a custom path on installation it errors.

**Comment by plicit** [comment]
@MarioGK , I implemented loading of the rootPath from your user's .config/scoop/config.json (where I think scoop is storing the path in your case).  I ran a few basic tests but I don't use that feature myself, so please let me know whether the new v0.1.20220728 works for you.

**Comment by MarioGK** [comment]
Thank you now it works perfectly

**Comment by Nightliss** [comment]
@plicit well now it's broken for default path 😂 
![image](https://user-images.githubusercontent.com/30467858/182878246-58cb25c5-e0ee-4275-94bf-e5c5a24842ed.png)

scoop config contains this:
![image](https://user-images.githubusercontent.com/30467858/182878471-8d76d80c-d456-4483-8c52-b17f4c42b872.png)

**Comment by plicit** [comment]
@Nightliss Sorry about that!  I think that has a slightly different cause.  I inserted a little code that searches the global scoop apps path for identifying already-installed apps, but you don't use global scoop apps so that directory doesn't exist which caused a fatal exit.  Please test the new [v0.1.20220804](https://github.com/plicit/scoop-search-multisource/releases/tag/v0.1.20220804) and let me know if you still have a problem.

**Comment by Nightliss** [comment]
Tried and works again. Many thanks for fix :). So much better than vanilla search option.
